### ISSUE TITLE
Is this a blog for rich people?

### ISSUE THREAD

**Issue by unexploredtest** [Aslemammad/Bugged.dev#1]
I heard that you have gained so much money recently, to an extent that 700 bitcoins seemed nothing to you, did you choose this blog because it's made for rich people?

**Comment by Aslemammad** [comment]
Yes, all of my audience are rich, too, because rich folks made this blog for rich folks. That's our line. We all transform bitcoin in this blog; it's a secret in the source.

**Comment by unexploredtest** [comment]
@Aslemammad  Wait, I'm one of the audiences. Why I'm not rich then?

**Comment by Aslemammad** [comment]
Maybe you aren't one of them.

**Comment by unexploredtest** [comment]
@Aslemammad You mean I'm not invited?
_Sob_

**Comment by Aslemammad** [comment]
Pretend like rich folks.

**Comment by unexploredtest** [comment]
I can't, I don't have the equipment, will you give me some?

**Comment by Aslemammad** [comment]
Yes, why not!

**Comment by unexploredtest** [comment]
When? You promised me once to give me an RTX 3090 and here we are.

**Comment by Aslemammad** [comment]
🤷🏻‍♂️

**Comment by unexploredtest** [comment]
So, it means I can't access the blog right? I'm so sad :(

**Comment by Aslemammad** [comment]
Don't be, get along with it.

**Comment by unexploredtest** [comment]
@Aslemammad You'll pay for that, you'll pay really really high!
